accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "bzip2-1.0.6",
    "CC0-1.0",
    "ISC",
    "MIT",
    "OFL-1.1",
    "Unicode-3.0",
    "Zlib",
]

# epaint_default_fonts includes fonts under OFL-1.1 and Ubuntu Font License.
# UFL-1.0 is not a standard SPDX identifier, so we clarify it here.
# The Ubuntu Font License is permissive and compatible with OFL-1.1.
[epaint_default_fonts.clarify]
license = "(MIT OR Apache-2.0) AND OFL-1.1"

[[epaint_default_fonts.clarify.files]]
path = "fonts/OFL.txt"
license = "OFL-1.1"
checksum = "6a73f9541c2de74158c0e7cf6b0a58ef774f5a780bf191f2d7ec9cc53efe2bf2"

[[epaint_default_fonts.clarify.files]]
path = "fonts/UFL.txt"
license = "OFL-1.1"
checksum = "2f0015108d68627bd788d313f529c21ff4da2c2c42a5e1f3883acc83480f9002"

[[epaint_default_fonts.clarify.files]]
path = "fonts/emoji-icon-font-mit-license.txt"
license = "MIT"
checksum = "b9d2c1d909aa149996fd4c91dcb92b2362a04431640c1d200959da94caf8cde1"

[[epaint_default_fonts.clarify.files]]
path = "fonts/Hack-Regular.txt"
license = "MIT"
checksum = "47c0cccbeec7e8614548cc485588b28149e7874188df5f41b36efebcee285c87"
