[workspace]
members = [
    "crates/vibe-emu-core",
    "crates/vibe-emu-ui",
    "crates/vibe-emu-mobile-sys",
    "crates/vibe-emu-mobile",
]
resolver = "2"

[patch.crates-io]
imgui-wgpu = { path = "vendor/imgui-wgpu-0.24.0" }
