[workspace]
members = [
    "crates/vibe-emu-core",
    "crates/vibe-emu-ui",
    "crates/vibe-emu-mobile-sys",
    "crates/vibe-emu-mobile",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2
