[package]
name = "vibe-emu-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
vibe-emu-core = { path = "../vibe-emu-core" }
clap = { version = "4", features = ["derive"] }
winit = { version = "0.30.12", features = ["rwh_05"] }
wgpu = "0.17"
pixels = "0.14"
imgui = { version = "0.12", features = ["docking", "tables-api"] }
imgui-winit-support = "0.13"
imgui-wgpu = "0.24"
cpal = "0.16"
rfd = { version = "0.15", default-features = false, features = ["gtk3"] }
png = "0.17"
